version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        command: "dotnet ef database update"
        ports:
            - 3500:80
        restart: on-failure
        depends_on:
            - postgres
        networks:
            - freeapinetwork
  
    postgres:
        image: postgres
        networks:
            - freeapinetwork

networks:
    freeapinetwork:
        driver: bridge